server:
  port: 8080
spring:
  application:
    name: log-demo-core
## Kafka 配置
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      bootstrap-servers: localhost:9092
## Redis配置
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 0
#    lettuce:
#      pool:
#        max-active: 10
#        min-idle: 5

dubbo:
  application:
    name: operator-log-demo
  registry:
    address: ${DUBBO_REGISTRY_ADDRESS:nacos://127.0.0.1:8848?namingLoadCacheAtStart=true}
  consumer:
    check: false
  metadata-report:
    address: ${dubbo.registry.address}
  config-center:
    address: ${dubbo.registry.address}

## RocketMQ 配置
rocketmq:
  name-server: localhost:9876
  producer:
    send-message-timeout: 2000
    compress-message-body-threshold: 4096
    group: OPERATOR_LOG_PRODUCER_GROUP