server:
  port: 8080
spring:
  application:
    name: log-demo-core
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      bootstrap-servers: localhost:9092
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        min-idle: 1

dubbo:
  application:
    id: operator-log-web
    qos-enable: false
    qos-port: 22224
    logger: slf4j
  registry:
    check: false
    address: zookeeper://127.0.0.1:2181
    simplified: true

#operator.log.mq.mode: kafka
operator.log.mq.mode: redis




#rocketmq:
#  name-server: localhost:9876
#  producer:
#    send-message-timeout: 2000
#    compress-message-body-threshold: 4096