CREATE TABLE `operation_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `module` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '模块',
  `operator` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '操作',
  `params` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '请求参数',
  `method` varchar(200) COLLATE utf8mb4_bin NOT NULL COMMENT '请求方法',
  `operation_type` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '操作类型',
  `operator_id` bigint(20) NOT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '操作人名称',
  `operator_ip` varchar(20) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '操作IP',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态 0 正常 1异常',
  `error_msg` varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '错误信息',
  `oper_time` datetime NOT NULL COMMENT '操作日期',
  `histry_record` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '历史数据',
  `model_parser` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作日志模型解析器',
  `desc` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作描述',
  `extra_json` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '扩展字段',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `create_by` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作人',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  `update_by` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新人',
  `tenant_id` int(11) DEFAULT NULL COMMENT '租户ID',
  `new_record` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '新数据',
  PRIMARY KEY (`id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_module` (`module`),
  KEY `idx_operator` (`operator`),
  KEY `idx_operator_id` (`operator_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;